# Site settings
title: Meta-Nonfiction
email: mdsumner@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A technical approach to fresh computing. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mdsumner
github_username:  mdsumner

# Build settings
markdown: kramdown
